In [ ]:
from google.colab import drive
drive.mount('/content/drive')
%cd /content/drive/MyDrive/
!mkdir -p 11868
%cd /content/drive/MyDrive/11868
!git clone https://github.com/llmsystem/llmsys_code_examples.git
%cd /content/drive/MyDrive/11868/llmsys_code_examples/cuda_demo

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
/content/drive/MyDrive
/content/drive/MyDrive/11868/test
Cloning into 'code_examples'...
remote: Enumerating objects: 17, done.
remote: Counting objects: 100% (17/17), done.
remote: Compressing objects: 100% (11/11), done.
remote: Total 17 (delta 3), reused 17 (delta 3), pack-reused 0
Receiving objects: 100% (17/17), 5.86 KiB | 750.00 KiB/s, done.
Resolving deltas: 100% (3/3), done.
/content/drive/MyDrive/11868/test/code_examples/cuda_demo


In [ ]:
!pip install pycuda

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 10.4 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 70.6/70.6 kB 9.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 78.6/78.6 kB 11.3 MB/s eta 0:00:00
  Created wheel for pycuda: filename=pycuda-2024.1-cp310-cp310-linux_x86_64.whl size=661205 sha256=87b18480433e8cc46e8387b1463bb1b1fa14bd3c2f1dcf7f9a33451b88e59872
  Stored in directory: /root/.cache/pip/wheels/12/34/d2/9a349255a4eca3a486d82c79d21e138ce2ccd90f414d9d72b8
Successfully built pycuda


## CUDA Example for Vector Add

We demonstrate how we can call C function in python file with ctypes with `VecAddCPU` function.

We also demonstrate two ways to write CUDA codes which can be called in python functions. The difference between them is that we create CUDA memory and copy the data to CUDA device by `pycuda` package in the `VecAddCUDA` function and `cudaMemcpy` in cpp codes in `VecAddCUDA2` function.

We use `pycuda` in assignment1 to call CUDA kernel functions.

In [ ]:
!nvcc -o vector_add.so --shared example_vector_add.cu -Xcompiler -fPIC

In [ ]:
!python test_vector_add.py

Input a: [7 5 1 7 6 4 7 3 9 3]
Input b: [8 4 2 6 5 1 7 7 8 6]
Numpy add: [15  9  3 13 11  5 14 10 17  9], <class 'numpy.ndarray'>
CPU add: [15  9  3 13 11  5 14 10 17  9], <class 'numpy.ndarray'>
GPU add: [15  9  3 13 11  5 14 10 17  9], <class 'pycuda.gpuarray.GPUArray'>
After offload: [15  9  3 13 11  5 14 10 17  9], <class 'numpy.ndarray'>
GPU add2: [15  9  3 13 11  5 14 10 17  9], <class 'numpy.ndarray'>


## CUDA Example for Window Sum

Demo of Window Sum to get to know synchronization in CUDA.

In [ ]:
!nvcc -o window_sum.so --shared example_window_sum.cu -Xcompiler -fPIC

In [ ]:
!python test_window_sum.py

Input: [ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12.]
Numpy window sum: [15. 20. 25. 30. 35. 40. 45. 50.]
GPU simple window sum: [15. 20. 25. 30. 35. 40. 45. 50.]
GPU shared window sum: [15. 20. 25. 30. 35. 40. 45. 50.]


## CUDA Example for Matrix Multiplication

Demo of matrix multiplication.

In [ ]:
!nvcc -o matmul.so --shared example_matmul.cu -Xcompiler -fPIC

In [ ]:
!python test_matmul.py

Input a: [[1. 2. 2. 1.]
 [2. 2. 2. 2.]
 [2. 2. 2. 1.]
 [1. 2. 1. 1.]]
Input b: [[1. 1.]
 [1. 2.]
 [1. 2.]
 [2. 1.]]
Numpy matmul: [[ 7. 10.]
 [10. 12.]
 [ 8. 11.]
 [ 6.  8.]], <class 'numpy.ndarray'>
GPU matmul: [[ 7. 10.]
 [10. 12.]
 [ 8. 11.]
 [ 6.  8.]], <class 'pycuda.gpuarray.GPUArray'>
After offload: [[ 7. 10.]
 [10. 12.]
 [ 8. 11.]
 [ 6.  8.]], <class 'numpy.ndarray'>
Compare result: 0.0
