In [ ]:
from google.colab import drive
drive.mount('/content/drive')
%cd /content/drive/MyDrive/
!mkdir -p 11868
!git clone https://github.com/llmsystem/code_examples.git
%cd /content/drive/MyDrive/11868/code_examples/cuda_demo

Mounted at /content/drive
/content/drive/MyDrive
/content/drive/MyDrive/11868/cuda_version


In [ ]:
!pip install pycuda

In [ ]:
!nvcc -o vector_add.so --shared example_vector_add.cu -Xcompiler -fPIC

In [ ]:
!python test_vector_add.py

Input a: [2 5 3 1 1 8 7 7 5 6]
Input b: [2 1 9 5 1 7 6 1 7 4]
Numpy add: [ 4  6 12  6  2 15 13  8 12 10], <class 'numpy.ndarray'>
CPU add: [ 4  6 12  6  2 15 13  8 12 10], <class 'numpy.ndarray'>
GPU add: [ 4  6 12  6  2 15 13  8 12 10], <class 'pycuda.gpuarray.GPUArray'>
After offload: [ 4  6 12  6  2 15 13  8 12 10], <class 'numpy.ndarray'>
GPU add2: [ 4  6 12  6  2 15 13  8 12 10], <class 'numpy.ndarray'>


In [211]:
!nvcc -o matmul.so --shared example_matmul.cu -Xcompiler -fPIC

In [212]:
!python test_matmul.py

Input a: [[1. 2. 2. 1.]
 [2. 2. 2. 2.]
 [2. 2. 2. 1.]
 [1. 2. 1. 1.]]
Input b: [[1. 1.]
 [1. 2.]
 [1. 2.]
 [2. 1.]]
Numpy matmul: [[ 7. 10.]
 [10. 12.]
 [ 8. 11.]
 [ 6.  8.]], <class 'numpy.ndarray'>
GPU matmul: [[ 7. 10.]
 [10. 12.]
 [ 8. 11.]
 [ 6.  8.]], <class 'pycuda.gpuarray.GPUArray'>
After offload: [[ 7. 10.]
 [10. 12.]
 [ 8. 11.]
 [ 6.  8.]], <class 'numpy.ndarray'>
Compare result: 0.0
block[0, 0], thread[0, 0], a_shared: 1.000000
block[0, 0], thread[1, 0], a_shared: 2.000000
block[0, 0], thread[0, 1], a_shared: 2.000000
block[0, 0], thread[1, 1], a_shared: 2.000000
block[1, 0], thread[0, 0], a_shared: 2.000000
block[1, 0], thread[1, 0], a_shared: 1.000000
block[1, 0], thread[0, 1], a_shared: 2.000000
block[1, 0], thread[1, 1], a_shared: 2.000000
block[0, 0], thread[0, 0], b_shared: 1.000000
block[0, 0], thread[1, 0], b_shared: 1.000000
block[0, 0], thread[0, 1], b_shared: 1.000000
block[0, 0], thread[1, 1], b_shared: 2.000000
block[1, 0], thread[0, 0], b_shared: 1.000000
bloc

In [ ]:
!nvcc -o window_sum.so --shared example_window_sum.cu -Xcompiler -fPIC

In [ ]:
!python test_window_sum.py

Input: [ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12.]
Numpy window sum: [15. 20. 25. 30. 35. 40. 45. 50.]
GPU simple window sum: [15. 20. 25. 30. 35. 40. 45. 50.]
GPU shared window sum: [15. 20. 25. 30. 35. 40. 45. 50.]
